package se.skl.skltpservices.ssekadapter.test.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2017-04-15T21:15:32.046+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "urn:riv:insuranceprocess:healthreporting:RegisterMedicalCertificate:3:rivtabp20", name = "SSEKRegisterMedicalCertificateResponderInterface")
@XmlSeeAlso({se.inera.ifv.registermedicalcertificateresponder.v3.ObjectFactory.class, org.w3.wsaddressing10.ObjectFactory.class, se.inera.mu7263.v3.ObjectFactory.class, se.inera.ifv.v2.ObjectFactory.class, iso.v21090.dt.v1.ObjectFactory.class, org.ssek.v2.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SSEKRegisterMedicalCertificateResponderInterface {

    @WebResult(name = "RegisterMedicalCertificateResponse", targetNamespace = "urn:riv:insuranceprocess:healthreporting:RegisterMedicalCertificateResponder:3", partName = "parameters")
    @WebMethod(operationName = "SSEKRegisterMedicalCertificate", action = "urn:riv:insuranceprocess:healthreporting:RegisterMedicalCertificateResponder:1")
    public se.inera.ifv.registermedicalcertificateresponder.v3.RegisterMedicalCertificateResponseType ssekRegisterMedicalCertificate(
        @WebParam(partName = "SSEKrequest", name = "SSEK", targetNamespace = "http://schemas.ssek.org/ssek/2006-05-10/", header = true)
        org.ssek.v2.SSEK sseKrequest,
        @WebParam(partName = "LogicalAddress", name = "To", targetNamespace = "http://www.w3.org/2005/08/addressing", header = true)
        org.w3.wsaddressing10.AttributedURIType logicalAddress,
        @WebParam(partName = "parameters", name = "RegisterMedicalCertificate", targetNamespace = "urn:riv:insuranceprocess:healthreporting:RegisterMedicalCertificateResponder:3")
        se.inera.ifv.registermedicalcertificateresponder.v3.RegisterMedicalCertificateType parameters
    );
}
